# HW 5 Question 2

# Setup

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, MinMaxScaler

import torch
import torch.optim as optim
torch.set_printoptions(edgeitems=2, linewidth=75)

## define model and functions

In [2]:
percent_for_validation = 0.2

In [29]:
def model(feature, w5, w4, w3, w2, w1, b):
    return feature[4] * w5 + feature[3] * w4 + feature[2] * w3 + feature[1] * w2 + feature[0] * w1 + b

In [4]:
def loss_function(predicted, actual):
    squared_diffs = (predicted - actual)**2
    return squared_diffs.mean()

In [5]:
rates_to_learn_at = [1/x for x in [10, 100, 1000, 10000, 100000]]
rates_to_learn_at

[0.1, 0.01, 0.001, 0.0001, 1e-05]

## Data import

In [6]:
housing_df = pd.DataFrame(pd.read_csv('Housing.csv'))
housing_df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [7]:
print(f"shape = {np.shape(housing_df)}")

# creates a list of all variables from the column names
feature_list = list( housing_df.columns )

print(f"features are: {feature_list}")

shape = (545, 13)
features are: ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']


In [8]:
# Maps to turn categorys into numbers 
def boolean_map(x):
    return x.map({'yes': 1 , 'no': 0})
def furnish_map(x):
    return x.map({'furnished': 1 , 'semi-furnished': 0.5 , 'unfurnished': 0})

# Extracts the yes and no column names
binary_vars = [*feature_list[5:10], feature_list[11]]
print(f"binary vars = {binary_vars}")

# Extracts the furnishing column names
furnish_vars = [feature_list[12]]
print(f"furnish vars = {furnish_vars}")

# Extracts the column names that are actual values
valued_vars = feature_list.copy()
[valued_vars.remove( item ) for item in binary_vars]
[valued_vars.remove( item ) for item in furnish_vars]
print(f"value vars = {valued_vars}")

binary vars = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
furnish vars = ['furnishingstatus']
value vars = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']


In [9]:
x_df = housing_df.copy()

## scale data
scaler = StandardScaler()
# scaler = MinMaxScaler()

x_df[valued_vars] = scaler.fit_transform(x_df[valued_vars])

## map text values
x_df[binary_vars] = x_df[binary_vars].apply(boolean_map)
x_df[furnish_vars] = x_df[furnish_vars].apply(furnish_map)

## make y_df
y_df = x_df.pop('price')


In [10]:
# input_values = valued_vars.copy()
# input_values.remove('price')


# x_df = x_df[input_values]

In [11]:
x_df.head()

area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
0  1.046726  1.403419   1.421812  1.378217         1          0         0   
1  1.757010  1.403419   5.405809  2.532024         1          0         0   
2  2.218232  0.047278   1.421812  0.224410         1          0         1   
3  1.083624  1.403419   1.421812  0.224410         1          0         1   
4  1.046726  1.403419  -0.570187  0.224410         1          1         1   

   hotwaterheating  airconditioning   parking  prefarea  furnishingstatus  
0                0                1  1.517692         1               1.0  
1                0                1  2.679409         0               1.0  
2                0                0  1.517692         1               0.5  
3                0                1  2.679409         1               1.0  
4                0                1  1.517692         0               1.0

In [12]:
y_df.head()

0    4.566365
1    4.004484
2    4.004484
3    3.985755
4    3.554979
Name: price, dtype: float64

In [13]:
# Remove unwanted data
for item in [*binary_vars, *furnish_vars] :
    x_df.pop(item)
x_df.head()

area  bedrooms  bathrooms   stories   parking
0  1.046726  1.403419   1.421812  1.378217  1.517692
1  1.757010  1.403419   5.405809  2.532024  2.679409
2  2.218232  0.047278   1.421812  0.224410  1.517692
3  1.083624  1.403419   1.421812  0.224410  2.679409
4  1.046726  1.403419  -0.570187  0.224410  1.517692

In [14]:
# Convert data frame to tensor

x = torch.tensor(x_df.values)
y = torch.tensor(y_df.values)

In [15]:
print(x.shape)
print("\n")
x

torch.Size([545, 5])




tensor([[ 1.0467,  1.4034,  ...,  1.3782,  1.5177],
        [ 1.7570,  1.4034,  ...,  2.5320,  2.6794],
        ...,
        [-1.0334,  0.0473,  ..., -0.9294, -0.8057],
        [-0.5998,  0.0473,  ...,  0.2244, -0.8057]], dtype=torch.float64)

In [16]:
print(y.shape)
print("\n")
y

torch.Size([545])




tensor([ 4.5664e+00,  4.0045e+00,  4.0045e+00,  3.9858e+00,  3.5550e+00,
         3.2553e+00,  2.8807e+00,  2.8807e+00,  2.7309e+00,  2.6934e+00,
         2.6934e+00,  2.6297e+00,  2.4312e+00,  2.3938e+00,  2.3938e+00,
         2.3188e+00,  2.3188e+00,  2.2439e+00,  2.2065e+00,  2.1877e+00,
         2.1315e+00,  2.0941e+00,  2.0754e+00,  2.0754e+00,  2.0379e+00,
         2.0192e+00,  1.9780e+00,  1.9443e+00,  1.9443e+00,  1.9443e+00,
         1.9443e+00,  1.9443e+00,  1.8881e+00,  1.8319e+00,  1.7944e+00,
         1.7735e+00,  1.7532e+00,  1.7195e+00,  1.7101e+00,  1.6820e+00,
         1.6633e+00,  1.6446e+00,  1.5697e+00,  1.5697e+00,  1.4947e+00,
         1.4947e+00,  1.4760e+00,  1.4573e+00,  1.4386e+00,  1.4198e+00,
         1.4198e+00,  1.4198e+00,  1.3824e+00,  1.3824e+00,  1.3824e+00,
         1.3824e+00,  1.3786e+00,  1.3262e+00,  1.3075e+00,  1.3075e+00,
         1.2700e+00,  1.2325e+00,  1.2325e+00,  1.2138e+00,  1.1951e+00,
         1.1576e+00,  1.1576e+00,  1.1389e+00,  1.1

In [17]:
x[1][0]

tensor(1.7570, dtype=torch.float64)

In [18]:
x[0][1]

tensor(1.4034, dtype=torch.float64)

In [19]:
x[:][0]

tensor([1.0467, 1.4034, 1.4218, 1.3782, 1.5177], dtype=torch.float64)

In [20]:
x[0][:]

tensor([1.0467, 1.4034, 1.4218, 1.3782, 1.5177], dtype=torch.float64)

In [21]:
x_t = x.transpose(-2, 1)
x_t.shape

torch.Size([5, 545])

In [22]:
x_t[1][:]

tensor([ 1.4034,  1.4034,  0.0473,  1.4034,  1.4034,  0.0473,  1.4034,
         2.7596,  1.4034,  0.0473,  0.0473,  1.4034,  1.4034,  1.4034,
         0.0473,  1.4034,  1.4034,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,
         2.7596,  1.4034,  0.0473,  0.0473,  1.4034,  0.0473,  2.7596,
         0.0473,  0.0473,  1.4034,  0.0473,  1.4034,  0.0473,  0.0473,
         0.0473,  1.4034,  1.4034,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,  0.0473,
         1.4034,  1.4034,  1.4034,  0.0473,  0.0473, -1.3089,  1.4034,
         1.4034,  0.0473,  0.0473, -1.3089,  0.0473,  0.0473,  1.4034,
         0.0473,  1.4034,  0.0473, -1.3089,  0.0473,  1.4034,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  2.7596,  0.0473,
        -1.3089,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,  0.0473,
      

In [23]:
x_t[:][1]

tensor([ 1.4034,  1.4034,  0.0473,  1.4034,  1.4034,  0.0473,  1.4034,
         2.7596,  1.4034,  0.0473,  0.0473,  1.4034,  1.4034,  1.4034,
         0.0473,  1.4034,  1.4034,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,
         2.7596,  1.4034,  0.0473,  0.0473,  1.4034,  0.0473,  2.7596,
         0.0473,  0.0473,  1.4034,  0.0473,  1.4034,  0.0473,  0.0473,
         0.0473,  1.4034,  1.4034,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,  0.0473,
         1.4034,  1.4034,  1.4034,  0.0473,  0.0473, -1.3089,  1.4034,
         1.4034,  0.0473,  0.0473, -1.3089,  0.0473,  0.0473,  1.4034,
         0.0473,  1.4034,  0.0473, -1.3089,  0.0473,  1.4034,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  0.0473,
         0.0473,  0.0473,  0.0473,  0.0473,  0.0473,  2.7596,  0.0473,
        -1.3089,  0.0473,  0.0473,  1.4034,  0.0473,  0.0473,  0.0473,
      

## Split into train and validation sets

In [24]:
n_samples = x.shape[0]
n_val = int(percent_for_validation * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices  # <1>

(tensor([330, 232, 145, 185, 457, 194, 266, 444, 182,  55,   7, 516, 536,
         183, 141, 440, 476,  23,  29,  69, 282,  25, 108, 407, 388, 350,
         268, 252, 479,  36, 320, 496, 253, 419, 509, 161, 163,  85, 488,
         504, 513, 453,  79, 213,  97, 519, 405,  28, 309, 345, 426,  49,
         326, 303, 178, 402,  77, 254, 462, 523, 358, 130, 114, 143, 248,
          12, 498,  39, 461, 466, 410, 450,  16,  45, 157, 292, 325, 492,
         208, 107, 172,  48, 352, 443, 533, 532,  47, 314, 520, 262,  88,
           6, 195, 249, 442, 416,  61, 201,  75, 404, 217, 480, 486, 164,
         428,  34,  87, 500, 104,  18, 135,   2, 151, 379, 354, 390, 403,
         382, 497, 142, 171, 275, 441, 429, 203, 166, 133, 211, 220,  40,
         356, 324, 273, 229, 300, 196, 338, 487, 448, 274, 264, 117, 342,
         515,  62, 214, 216, 234, 173, 246, 198, 294, 483, 265, 401,  27,
           8,  33, 335,  21,  58, 505, 256, 490,   4,  38, 353, 417,  57,
         210,   5, 176, 180, 199, 424,

In [25]:
training_x = x[train_indices]
training_y  = y [train_indices]

validation_x = x[val_indices]
validation_y  = y[val_indices]

# training_un   = 0.1 * training_feature
# validation_un = 0.1 * validation_feature

## Define the training

In [26]:
def training_loop(n_epochs, optimizer, params, 
                  train_x, val_x,
                  train_y, val_y):
    for epoch in range(1, n_epochs + 1):
        train_predicted = model(train_x.transpose(-2, 1), *params)
        train_loss = loss_function(train_predicted, train_y)

        # For the valudation step
        with torch.no_grad(): 
            val_predicted = model(val_x.transpose(-2, 1), *params)
            val_loss = loss_function(val_predicted, val_y)
            assert val_loss.requires_grad == False # <2>
            
        optimizer.zero_grad()
        
        train_loss.backward()
        optimizer.step()
        
        if epoch <= 3 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

# Results

In [30]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params,
    train_x = training_x, # <1> 
    val_x = validation_x, # <1> 
    train_y = training_y,
    val_y = validation_y)

params

Epoch 1, Training loss 5.5141, Validation loss 8.2283
Epoch 2, Training loss 5.5106, Validation loss 8.2230
Epoch 3, Training loss 5.5070, Validation loss 8.2177
Epoch 500, Training loss 4.0157, Validation loss 5.9960
Epoch 1000, Training loss 2.9606, Validation loss 4.4107
Epoch 1500, Training loss 2.2191, Validation loss 3.2856
Epoch 2000, Training loss 1.6978, Validation loss 2.4856
Epoch 2500, Training loss 1.3312, Validation loss 1.9153
Epoch 3000, Training loss 1.0731, Validation loss 1.5077
Epoch 3500, Training loss 0.8913, Validation loss 1.2154
Epoch 4000, Training loss 0.7632, Validation loss 1.0051
Epoch 4500, Training loss 0.6727, Validation loss 0.8531
Epoch 5000, Training loss 0.6087, Validation loss 0.7428


tensor([0.4142, 0.3865, 0.3929, 0.2513, 0.4349, 0.0102],
       requires_grad=True)

In [ ]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params,
    train_t_u = training_t_un, # <1> 
    val_t_u = validation_t_un, # <1> 
    train_t_c = training_output,
    val_t_c = validation_output)

params