In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# test model found on internet
class test_class(nn.Module):
    def __init__(self):
        super(test_class, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [3]:
# Define test model
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()
        self.test_val = 5
        self.test_tensor = torch.tensor([5])
        self.test_param = nn.parameter.Parameter(self.test_tensor, False)
        self.new_param = nn.parameter.Parameter(torch.tensor([[5, 7, 5], [1, 4, 6]]), False)
        self.test_model = test_class()
        self.optimizer = optim.SGD(self.test_model.parameters(), lr=0.001, momentum=0.9)

    def forward(self):
        self.optimizer.zero_grad()
        self.test_model.forward()
        self.optimizer.step()

In [4]:
# Initialize model
model = TheModelClass()

In [5]:
# Print model's state_dict
print("Model's state_dict:")
for params in model.state_dict():
    print(params, "\t", model.state_dict()[params].size())

Model's state_dict:
test_param 	 torch.Size([1])
new_param 	 torch.Size([2, 3])
test_model.conv1.weight 	 torch.Size([6, 3, 5, 5])
test_model.conv1.bias 	 torch.Size([6])
test_model.conv2.weight 	 torch.Size([16, 6, 5, 5])
test_model.conv2.bias 	 torch.Size([16])
test_model.fc1.weight 	 torch.Size([120, 400])
test_model.fc1.bias 	 torch.Size([120])
test_model.fc2.weight 	 torch.Size([84, 120])
test_model.fc2.bias 	 torch.Size([84])
test_model.fc3.weight 	 torch.Size([10, 84])
test_model.fc3.bias 	 torch.Size([10])


In [6]:
# Print inside state_dict
print("test_model's state_dict:")
for params in model.test_model.state_dict():
    print(params, "\t", (model.test_model).state_dict()[params].size())

test_model's state_dict:
conv1.weight 	 torch.Size([6, 3, 5, 5])
conv1.bias 	 torch.Size([6])
conv2.weight 	 torch.Size([16, 6, 5, 5])
conv2.bias 	 torch.Size([16])
fc1.weight 	 torch.Size([120, 400])
fc1.bias 	 torch.Size([120])
fc2.weight 	 torch.Size([84, 120])
fc2.bias 	 torch.Size([84])
fc3.weight 	 torch.Size([10, 84])
fc3.bias 	 torch.Size([10])


In [7]:
test_save = "test_model/model.pt"

In [8]:
torch.save(model.state_dict(), test_save)

In [9]:
load_model = TheModelClass()
load_model.load_state_dict(torch.load(test_save))

<All keys matched successfully>

In [10]:
# Print model's state_dict
print("Model's state_dict:")
for params in load_model.state_dict():
    print(params, "\t", load_model.state_dict()[params].size())

Model's state_dict:
test_param 	 torch.Size([1])
new_param 	 torch.Size([2, 3])
test_model.conv1.weight 	 torch.Size([6, 3, 5, 5])
test_model.conv1.bias 	 torch.Size([6])
test_model.conv2.weight 	 torch.Size([16, 6, 5, 5])
test_model.conv2.bias 	 torch.Size([16])
test_model.fc1.weight 	 torch.Size([120, 400])
test_model.fc1.bias 	 torch.Size([120])
test_model.fc2.weight 	 torch.Size([84, 120])
test_model.fc2.bias 	 torch.Size([84])
test_model.fc3.weight 	 torch.Size([10, 84])
test_model.fc3.bias 	 torch.Size([10])


In [11]:
# Print inside state_dict
print("test_model's state_dict:")
for params in load_model.test_model.state_dict():
    print(params, "\t", (load_model.test_model).state_dict()[params].size())

test_model's state_dict:
conv1.weight 	 torch.Size([6, 3, 5, 5])
conv1.bias 	 torch.Size([6])
conv2.weight 	 torch.Size([16, 6, 5, 5])
conv2.bias 	 torch.Size([16])
fc1.weight 	 torch.Size([120, 400])
fc1.bias 	 torch.Size([120])
fc2.weight 	 torch.Size([84, 120])
fc2.bias 	 torch.Size([84])
fc3.weight 	 torch.Size([10, 84])
fc3.bias 	 torch.Size([10])


In [12]:
load_model.test_param

Parameter containing:
tensor([5])

In [13]:
load_model.test_param.data

tensor([5])

In [14]:
(load_model.test_param) + 5

tensor([10])

In [15]:
(load_model.test_param).data + 5

tensor([10])

In [16]:
load_model.new_param

Parameter containing:
tensor([[5, 7, 5],
        [1, 4, 6]])

In [17]:
load_model.new_param.data

tensor([[5, 7, 5],
        [1, 4, 6]])

In [18]:
(load_model.new_param) + 5

tensor([[10, 12, 10],
        [ 6,  9, 11]])

In [19]:
(load_model.new_param).data + 5

tensor([[10, 12, 10],
        [ 6,  9, 11]])

In [30]:
load_model.test_param.data.item()

5

In [31]:
load_model.test_param.item()

5